name: GVM Deploy
on:
  workflow_dispatch:
jobs:
  gvm-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3   

    - name: 📩 Deploy to custom domain
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ourtimecapsule.org
        username: gvm@ourtimecapsule.org
        password: ${{secrets.FTP_PASSWORD}}
        server-dir: ourtimecapsule.org/public_html/
        protocol: ftps
        dangerous-clean-slate: true
